version: '3.8'
services:
  db:
    image: mysql:8
    container_name: trip_db
    restart: always
    environment:
      MYSQL_DATABASE: tripdb
      MYSQL_USER: viethan
      MYSQL_PASSWORD: viethanpwd
      MYSQL_ROOT_PASSWORD: viethanroot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  mysql_data:
